import { useEffect, useState } from "react";
import { api, session, isCueStaff } from "./api.js";
import { CueBracket, Wordmark } from "./components/Mark.jsx";
import Login from "./components/Login.jsx";
import SetPassword from "./components/SetPassword.jsx";
import Health from "./components/Health.jsx";
import Tenants from "./components/Tenants.jsx";
import Staff from "./components/Staff.jsx";
import Plates from "./components/Plates.jsx";
import Retention from "./components/Retention.jsx";
import LensSim from "./components/LensSim.jsx";
import Architecture from "./components/Architecture.jsx";
import Brand from "./components/Brand.jsx";
import Doc from "./components/Doc.jsx";
import Decode, { prefersReducedMotion } from "./components/Decode.jsx";
// Generated by `npm run docs:sync` from the repo root — see scripts/sync-docs.mjs.
import featuresMd from "./docs/features.md?raw";
import onboardingMd from "./docs/onboarding.md?raw";

/**
 * Shell.
 *
 * Left rail rather than a top tab strip. Two reasons beyond convention: the
 * panels here are destinations you sit in rather than tabs you flick between,
 * and a vertical list has room to grow — billing, audit and support views are
 * all coming, and a horizontal strip starts wrapping at about six.
 */
const SECTIONS = [
  {
    label: "Platform",
    items: [
      { key: "health", name: "Health", hint: "services and checks" },
      { key: "tenants", name: "Tenants", hint: "retailers, people, billing" },
      { key: "staff", name: "CueSea staff", hint: "us, and who can sign in" },
      { key: "plates", name: "Plates", hint: "printed doors, and revocation" },
      { key: "retention", name: "Retention", hint: "windows, and what was deleted" },
      // Last in Platform rather than under Reference: it is a thing you drive,
      // not a thing you read.
      { key: "lens-sim", name: "Lens Sim", hint: "the Meta lens, no hardware" },
    ],
  },
  {
    label: "Reference",
    items: [
      { key: "architecture", name: "Architecture", hint: "how it all fits" },
      { key: "features", name: "What CueSea does", hint: "built, partial, not built" },
      { key: "onboarding", name: "Onboarding", hint: "adding a retailer, step by step" },
      { key: "onepager", name: "Employee one-pager", hint: "print this for the floor" },
      { key: "brand", name: "Brand", hint: "tokens, mark, voice" },
    ],
  },
];

const TITLES = {
  health: ["Health", "What the platform can prove about itself right now."],
  staff: ["CueSea staff", "Accounts with no tenant. Invite a colleague, change a role, end a session."],
  tenants: ["Tenants", "Every retailer, their people, their hardware, what they've used."],
  retention: ["Retention", "Each store's window, and what the last sweep actually deleted."],
  plates: ["Plates", "Every printed door, how hard each is being used, and the one control that matters."],
  "lens-sim": ["Lens Sim", "The Meta lens, running the bundle the glasses run, with nothing to plug in."],
  architecture: ["Architecture", "The system, the decisions behind it, and what's still missing."],
  features: ["What CueSea does", "Read off the code, not the roadmap — and honest about the difference."],
  onboarding: ["Onboarding a retailer", "Console only. No terminal, no code."],
  onepager: ["Employee one-pager", "Turn on, pair, control. Print it and put it in the stock room."],
  brand: ["Brand & identity", "Generated from the same tokens that build the products."],
};

/** The one path this app answers on other than `/`. Read once, before React
 *  renders anything, because the answer cannot change without a navigation. */
function invitedToken() {
  if (typeof window === "undefined") return null;
  if (!window.location.pathname.startsWith("/set-password")) return null;
  return new URLSearchParams(window.location.search).get("token") || "";
}

export default function App() {
  const [user, setUser] = useState(session.user);
  const [checking, setChecking] = useState(Boolean(session.token));
  const [view, setView] = useState("health");
  const [navOpen, setNavOpen] = useState(false);
  const [invite, setInvite] = useState(invitedToken);

  // The boot sequence is scan → resolve → settle into glass, and the glass is
  // the last step: `.rail.booting` carries the sweep and withholds the blur, so
  // the rail arrives solid, is scanned once, and only then becomes a lens. With
  // reduced motion there is no sequence to wait for — it starts settled.
  const [booting, setBooting] = useState(() => !prefersReducedMotion());
  useEffect(() => {
    if (!booting) return undefined;
    const t = setTimeout(() => setBooting(false), 1100);
    return () => clearTimeout(t);
  }, []);

  // A stored token may have been revoked since the tab was opened. Confirm it
  // before rendering panels that would 401 one at a time and look broken.
  useEffect(() => {
    if (!session.token) return;
    api.me()
      .then(({ user: fresh }) => { setUser(fresh); session.save(session.token, fresh); })
      .catch(() => { session.clear(); setUser(null); })
      .finally(() => setChecking(false));
  }, []);

  async function signOut() {
    await api.logout();
    session.clear();
    setUser(null);
  }

  // Before the session check, not after. Somebody redeeming an invitation has
  // no session by definition, and an expired token left in this tab must not
  // send them to a spinner or a sign-in form instead of the link they clicked.
  if (invite !== null) {
    return (
      <SetPassword
        token={invite}
        onDone={() => {
          // Clear the token out of the address bar on the way to sign-in. It
          // is spent, and leaving it in history or in a screenshot is a
          // credential lying around for no reason.
          window.history.replaceState({}, "", "/");
          setInvite(null);
        }}
      />
    );
  }

  if (checking) {
    return <div className="console"><div className="empty">Checking your session…</div></div>;
  }
  if (!user) return <Login onSignedIn={setUser} />;

  // Belt and braces. The API refuses these accounts on every route anyway;
  // this exists so a retailer's admin who lands here reads a sentence instead
  // of a shell that fails one panel at a time.
  if (!isCueStaff(user)) {
    return (
      <div className="signin-wrap">
        <div className="signin">
          <Wordmark size={22} />
          <div className="notice error">
            This console is for cuesea staff. Your account is a{" "}
            <strong>{user.role.replace("_", " ")}</strong>
            {user.tenant_slug ? <> at <span className="ident">{user.tenant_slug}</span></> : null}
            {" "}— everything you need is in Studio.
          </div>
          <div className="btn-row">
            <a className="btn primary" href="https://app.cuesea.ai">Open Studio</a>
            <button className="btn ghost" onClick={signOut}>Sign out</button>
          </div>
        </div>
      </div>
    );
  }

  const [title, subtitle] = TITLES[view];

  function go(key) {
    setView(key);
    setNavOpen(false);   // on a phone the rail is an overlay; close it behind you
  }

  return (
    <div className={`shell ${navOpen ? "nav-open" : ""}`}>
      <aside className={`rail ${booting ? "booting" : ""}`}>
        <div className="rail-brand">
          <Wordmark size={19} />
        </div>
        {/* The arc takes the ground — paper on dark — and never the cue's
            colour; the flame in this region is the word "staff", which is the
            one thing here asking to be noticed. */}
        <div className="rail-role">
          <CueBracket size={13} arc="var(--paper)" />
          <span>Console · staff</span>
        </div>

        <nav className="rail-nav">
          {SECTIONS.map((section) => (
            <div className="rail-section" key={section.label}>
              <div className="rail-section-label">{section.label}</div>
              {section.items.map((item) => (
                <button
                  key={item.key}
                  className={`rail-item ${view === item.key ? "active" : ""}`}
                  onClick={() => go(item.key)}
                  aria-current={view === item.key ? "page" : undefined}
                >
                  {/* Decoded once, on boot. The list never changes, so there
                      is nothing here to re-scramble. */}
                  <Decode as="span" className="rail-item-name" text={item.name} />
                  <span className="rail-item-hint">{item.hint}</span>
                </button>
              ))}
            </div>
          ))}
        </nav>

        <div className="rail-foot">
          <div className="rail-user" title={user.email}>{user.email}</div>
          <button className="linkish" onClick={signOut}>Sign out</button>
        </div>
      </aside>

      {/* Tapping the dimmed content closes the rail on a phone. */}
      <div className="rail-scrim" onClick={() => setNavOpen(false)} aria-hidden="true" />

      <div className="main">
        <header className="main-head">
          <button className="nav-toggle" onClick={() => setNavOpen((v) => !v)}
                  aria-label="Menu" aria-expanded={navOpen}>
            <span /><span /><span />
          </button>
          <div>
            {/* On first paint and again on every panel entered — `view` is the
                replay key, so arriving somewhere always resolves. The sentence
                below it is a person talking and stays still. */}
            <Decode as="h1" className="main-title" text={title} replay={view} />
            <p className="main-sub">{subtitle}</p>
          </div>
        </header>

        <div className="main-body">
          {view === "health" && <Health />}
          {view === "tenants" && <Tenants />}
          {view === "staff" && <Staff />}
          {view === "plates" && <Plates />}
          {view === "retention" && <Retention />}
          {view === "lens-sim" && <LensSim />}
          {view === "architecture" && <Architecture />}
          {view === "features" && (
            <div className="card span-12"><Doc source={featuresMd} /></div>
          )}
          {view === "onboarding" && (
            <div className="card span-12"><Doc source={onboardingMd} /></div>
          )}
          {view === "onepager" && (
            <div className="card span-12">
              <div className="card-head">
                <h3>One page, for whoever is wearing them</h3>
                <a className="dl-all" href="/docs/cue-employee-one-pager.pdf"
                   target="_blank" rel="noreferrer">Print-ready PDF</a>
              </div>
              <p className="card-note">
                A4. Generated from the same gesture table the plugin runs, so it
                cannot drift from the glasses — a printed control scheme goes
                wrong silently, on a wall nobody re-reads.
              </p>
              <img className="onepager" alt="CueSea employee one-pager"
                   src="/docs/cue-employee-one-pager.svg" />
            </div>
          )}
          {view === "brand" && <Brand />}
        </div>
      </div>
    </div>
  );
}
