import { useEffect, useState } from "react";
import { api, session, isCueStaff } from "./api.js";
import { CueBracket, Wordmark } from "./components/Mark.jsx";
import Login from "./components/Login.jsx";
import Health from "./components/Health.jsx";
import Tenants from "./components/Tenants.jsx";
import Architecture from "./components/Architecture.jsx";
import Brand from "./components/Brand.jsx";
import Doc from "./components/Doc.jsx";
// Generated by `npm run docs:sync` from the repo root — see scripts/sync-docs.mjs.
import featuresMd from "./docs/features.md?raw";
import onboardingMd from "./docs/onboarding.md?raw";

/**
 * Shell.
 *
 * Left rail rather than a top tab strip. Two reasons beyond convention: the
 * panels here are destinations you sit in rather than tabs you flick between,
 * and a vertical list has room to grow — billing, audit and support views are
 * all coming, and a horizontal strip starts wrapping at about six.
 */
const SECTIONS = [
  {
    label: "Platform",
    items: [
      { key: "health", name: "Health", hint: "services and checks" },
      { key: "tenants", name: "Tenants", hint: "retailers, people, billing" },
    ],
  },
  {
    label: "Reference",
    items: [
      { key: "architecture", name: "Architecture", hint: "how it all fits" },
      { key: "features", name: "What Cue does", hint: "built, partial, not built" },
      { key: "onboarding", name: "Onboarding", hint: "adding a retailer, step by step" },
      { key: "brand", name: "Brand", hint: "tokens, mark, voice" },
    ],
  },
];

const TITLES = {
  health: ["Health", "What the platform can prove about itself right now."],
  tenants: ["Tenants", "Every retailer, their people, their hardware, what they've used."],
  architecture: ["Architecture", "The system, the decisions behind it, and what's still missing."],
  features: ["What Cue does", "Read off the code, not the roadmap — and honest about the difference."],
  onboarding: ["Onboarding a retailer", "Console only. No terminal, no code."],
  brand: ["Brand & identity", "Generated from the same tokens that build the products."],
};

export default function App() {
  const [user, setUser] = useState(session.user);
  const [checking, setChecking] = useState(Boolean(session.token));
  const [view, setView] = useState("health");
  const [navOpen, setNavOpen] = useState(false);

  // A stored token may have been revoked since the tab was opened. Confirm it
  // before rendering panels that would 401 one at a time and look broken.
  useEffect(() => {
    if (!session.token) return;
    api.me()
      .then(({ user: fresh }) => { setUser(fresh); session.save(session.token, fresh); })
      .catch(() => { session.clear(); setUser(null); })
      .finally(() => setChecking(false));
  }, []);

  async function signOut() {
    await api.logout();
    session.clear();
    setUser(null);
  }

  if (checking) {
    return <div className="console"><div className="empty">Checking your session…</div></div>;
  }
  if (!user) return <Login onSignedIn={setUser} />;

  // Belt and braces. The API refuses these accounts on every route anyway;
  // this exists so a retailer's admin who lands here reads a sentence instead
  // of a shell that fails one panel at a time.
  if (!isCueStaff(user)) {
    return (
      <div className="signin-wrap">
        <div className="signin">
          <Wordmark size={22} />
          <div className="notice error">
            This console is for cuesea staff. Your account is a{" "}
            <strong>{user.role.replace("_", " ")}</strong>
            {user.tenant_slug ? <> at <span className="ident">{user.tenant_slug}</span></> : null}
            {" "}— everything you need is in Cue Studio.
          </div>
          <div className="btn-row">
            <a className="btn primary" href="https://app.cuesea.ai">Open Cue Studio</a>
            <button className="btn ghost" onClick={signOut}>Sign out</button>
          </div>
        </div>
      </div>
    );
  }

  const [title, subtitle] = TITLES[view];

  function go(key) {
    setView(key);
    setNavOpen(false);   // on a phone the rail is an overlay; close it behind you
  }

  return (
    <div className={`shell ${navOpen ? "nav-open" : ""}`}>
      <aside className="rail">
        <div className="rail-brand">
          <Wordmark size={19} />
        </div>
        <div className="rail-role">
          <CueBracket size={13} arc="var(--flame-300)" />
          <span>Cue Console · staff</span>
        </div>

        <nav className="rail-nav">
          {SECTIONS.map((section) => (
            <div className="rail-section" key={section.label}>
              <div className="rail-section-label">{section.label}</div>
              {section.items.map((item) => (
                <button
                  key={item.key}
                  className={`rail-item ${view === item.key ? "active" : ""}`}
                  onClick={() => go(item.key)}
                  aria-current={view === item.key ? "page" : undefined}
                >
                  <span className="rail-item-name">{item.name}</span>
                  <span className="rail-item-hint">{item.hint}</span>
                </button>
              ))}
            </div>
          ))}
        </nav>

        <div className="rail-foot">
          <div className="rail-user" title={user.email}>{user.email}</div>
          <button className="linkish" onClick={signOut}>Sign out</button>
        </div>
      </aside>

      {/* Tapping the dimmed content closes the rail on a phone. */}
      <div className="rail-scrim" onClick={() => setNavOpen(false)} aria-hidden="true" />

      <div className="main">
        <header className="main-head">
          <button className="nav-toggle" onClick={() => setNavOpen((v) => !v)}
                  aria-label="Menu" aria-expanded={navOpen}>
            <span /><span /><span />
          </button>
          <div>
            <h1 className="main-title">{title}</h1>
            <p className="main-sub">{subtitle}</p>
          </div>
        </header>

        <div className="main-body">
          {view === "health" && <Health />}
          {view === "tenants" && <Tenants />}
          {view === "architecture" && <Architecture />}
          {view === "features" && (
            <div className="card span-12"><Doc source={featuresMd} /></div>
          )}
          {view === "onboarding" && (
            <div className="card span-12"><Doc source={onboardingMd} /></div>
          )}
          {view === "brand" && <Brand />}
        </div>
      </div>
    </div>
  );
}
