"""The Cue mark, sized for the lens.

The store icon (make-icons.py) is 1024px on a coloured-ish background. This is
the same construction — 32-grid, r=11, 70 degree gap on the 3 o'clock axis,
cue r=2.9 at optical centre — drawn at 28px for the header of the HUD.

Two things change at this size, and both are forced by the hardware:

  Polarity. The lens is additive: unlit is black and there is no "paper". So
  the arc is drawn at full brightness on black rather than paper on sea-900.

  Tone. The host converts whatever it is handed to gray-4, sixteen levels. The
  cue keeps its tonal step down from the arc — flame's luminance relative to
  paper's — because that step is what makes it read as a separate element
  rather than a thickening of the stroke. Sixteen levels is enough to hold one
  step; it is not enough to hold a gradient, so the mark is supersampled and
  then quantised deliberately instead of being left to the host's dithering.

Writes src/mark.ts: the PNG inlined as base64. Inlined rather than fetched
because the glasses load this over BLE-adjacent transport and a second request
for 400 bytes is a request that can fail on a shop floor; and because a
missing asset would show as an empty box in the one place the brand is.

    python3 packages/glasses-plugin/store/make-lens-mark.py
"""
import base64
import io
import math
import textwrap

from PIL import Image, ImageDraw

# The container is 28x28 (host minimum is 20). Everything else is derived.
S = 28
SCALE = 16
G = S / 32.0


def lum(hexstr):
    r, g, b = (int(hexstr[i:i + 2], 16) / 255 for i in (1, 3, 5))
    f = lambda c: c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    y = 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)
    return (y ** (1 / 2.2))


# Paper is the brightest thing the mark contains, so it maps to lit. Flame
# keeps its ratio against paper — the same step down it has on a printed page.
PAPER_Y, FLAME_Y = lum("#FBF9F5"), lum("#FF6B2C")
PAPER = 255
FLAME = max(1, int(round(255 * FLAME_Y / PAPER_Y)))
print(f"paper {PAPER}  flame {FLAME}  (gray4 levels: {PAPER // 17}, {FLAME // 17})")

img = Image.new("L", (S * SCALE, S * SCALE), 0)
d = ImageDraw.Draw(img)

c = 16 * G * SCALE
r = 11 * G * SCALE
stroke = 4.0 * G * SCALE
cue_r = 2.9 * G * SCALE

d.arc([c - r, c - r, c + r, c + r], start=35, end=325, fill=PAPER, width=int(stroke))
# PIL draws butt ends and grows an arc's width inward, so the centreline sits
# at r - stroke/2. Round caps go there, matching the construction spec.
rc = r - stroke / 2
for deg in (35, -35):
    a = math.radians(deg)
    ex, ey = c + rc * math.cos(a), c + rc * math.sin(a)
    d.ellipse([ex - stroke / 2, ey - stroke / 2, ex + stroke / 2, ey + stroke / 2], fill=PAPER)
d.ellipse([c - cue_r, c - cue_r, c + cue_r, c + cue_r], fill=FLAME)

img = img.resize((S, S), Image.LANCZOS)

# Quantise to the sixteen levels the host will end up with anyway. Doing it
# here means the mark that ships is the mark that renders — the alternative is
# discovering on glass that the host's own reduction ate the cue.
img = img.point(lambda v: (v // 17) * 17)

buf = io.BytesIO()
img.save(buf, format="PNG", optimize=True)
png = buf.getvalue()
b64 = base64.b64encode(png).decode()
print(f"{len(png)} bytes png, {len(b64)} bytes base64")

img.resize((S * 8, S * 8), Image.NEAREST).save("/tmp/lens-mark-8x.png")

body = "\n".join(f'  "{chunk}" +' for chunk in textwrap.wrap(b64, 76))
body = body.rstrip(" +") + ";"

with open("packages/glasses-plugin/src/mark.ts", "w") as fh:
    fh.write(f'''/**
 * The Cue mark, {S}x{S}, as PNG bytes.
 *
 * GENERATED by store/make-lens-mark.py — do not edit by hand.
 *
 * Inlined rather than fetched: it is 400 bytes, it is the one place the brand
 * appears on the glass, and a second network request on a shop floor is a
 * second thing that can fail. Already quantised to gray-4, so the host's own
 * reduction has nothing left to take.
 */
export const MARK_W = {S};
export const MARK_H = {S};

const MARK_B64 =
{body}

/** PNG bytes for `updateImageRawData`. Decoded once, on first use. */
let bytes: Uint8Array | null = null;
export function markBytes(): Uint8Array {{
  if (!bytes) {{
    const bin = atob(MARK_B64);
    bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  }}
  return bytes;
}}
''')
print("wrote packages/glasses-plugin/src/mark.ts")
