/**
 * The Cue mark, 28x28, as PNG bytes.
 *
 * GENERATED by store/make-lens-mark.py — do not edit by hand.
 *
 * Inlined rather than fetched: it is 400 bytes, it is the one place the brand
 * appears on the glass, and a second network request on a shop floor is a
 * second thing that can fail. Already quantised to gray-4, so the host's own
 * reduction has nothing left to take.
 */
export const MARK_W = 28;
export const MARK_H = 28;

const MARK_B64 =
  "iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAAAAABXZoBIAAAA2ElEQVR42sWSUW3EMBBEX08lsBRM" +
  "wRRCIRRCIRSuVFoIKQQHggNhDGH6cTnVl0v72a5kyfbMajzjhb+vl24/5MS2fp7R5mrbdp2foFRs" +
  "6bZKOmDVslWKbFmPaLFcp4CYquUavZ7lZb+IxXLuwCp15OKl92B5AmIYAuDe9wqQG+0DYg6Gtwbr" +
  "Dl4AUsTWIEdr0atdfovvArC1lgLWFtHWI2OwPJ486NsKP1i5hXA/vB9CoFguY0CM5RgfSXvw1Zb1" +
  "KEoutmxbds1Ppq77Z+saJ2MS+5g0/rO+AH+KlPa3mdj4AAAAAElFTkSuQmCC";

/** PNG bytes for `updateImageRawData`. Decoded once, on first use. */
let bytes: Uint8Array | null = null;
export function markBytes(): Uint8Array {
  if (!bytes) {
    const bin = atob(MARK_B64);
    bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  }
  return bytes;
}
